server {
    listen 443 ssl;
    server_name api.360ingeco.com;

    ssl_certificate /etc/ssl/certs/api.360ingeco.com.crt;
    ssl_certificate_key /etc/ssl/private/api.360ingeco.com.key;

    location / {
        proxy_pass http://backend:8000;  # Redirigir tráfico al contenedor del backend (Django)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 80;
    server_name api.360ingeco.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name safe.360ingeco.com;

    ssl_certificate /etc/ssl/certs/safe.360ingeco.com.crt;
    ssl_certificate_key /etc/ssl/private/safe.360ingeco.com.key;

    location / {
        proxy_pass http://frontend:3000;  # Redirigir tráfico al contenedor del frontend (Next.js)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 80;
    server_name safe.360ingeco.com;
    return 301 https://$host$request_uri;
}
